# Project information
site_name: OSIPI Documentation Hub
site_url: https://osipi.github.io/pypi/

# Repository
repo_name: OSIPI/pypi
repo_url: https://github.com/OSIPI/pypi
copyright: Copyright © 2025 OSIPI Team

# Configuration
theme:
  name: material
  logo: img/osipi.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - tables

  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - multirepo:
      cleanup: false
      nav_repos:
        - name: osipi
          import_url: 'https://github.com/OSIPI/osipi?branch=main'
          imports: [docs/*, src/*]

  # - mkdocstrings:
  #     handlers: 
  #       python:
  #         paths: ["temp_dir/osipi/src"]

  # - gallery:
  #      examples_dirs: temp_dir/osipi/docs/examples
  #      gallery_dirs: docs/generated/gallery

nav:
  - Osipi:
    - Home: osipi/docs/index.md
    - User Guide:
        - Overview: osipi/docs/user-guide/index.md
        - Installation: osipi/docs/user-guide/install.md
        - Simulating data:
            - Overview: osipi/docs/user-guide/simulate.md
            - Simulate: osipi/docs/user-guide/gen_aif.md
        - Fitting data:
            - Overview: osipi/docs/user-guide/fitting.md
            - Fit: osipi/docs/user-guide/fit_tissue.md

    - About: osipi/docs/about/index.md
    - Developer Guide: osipi/docs/contribution/index.md
    - References:
        - osipi/docs/references/index.md
        - Index:
            - osipi/docs/references/models/index.md
            - AIF models:
                - osipi/docs/references/models/aif_models/index.md
                - osipi.aif_parker: osipi/docs/references/models/aif_models/aif_parker.md
                - osipi.aif_georgiou: osipi/docs/references/models/aif_models/aif_georgiou.md
                - osipi.aif_weinmann: osipi/docs/references/models/aif_models/aif_weinmann.md
            - Tissue models :
                - osipi/docs/references/models/tissue_models/index.md
                - osipi.tofts: osipi/docs/references/models/tissue_models/tofts.md
                - osipi.extended_tofts: osipi/docs/references/models/tissue_models/extended_tofts.md
    - Examples: generated/gallery

extra_css:
  - stylesheets/extra.css

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
        alternate_style: true
  - attr_list