# Project information
site_name: OSIPI Documentation  # Add a proper site name
site_url: https://osipi.github.io/pypi  # Assuming this is your site URL; adjust if needed
site_author: OSIPI Team  # Add your team/author name
site_description: >- 
  Open Source Initiative for Perfusion Imaging (OSIPI) documentation – simulate and fit perfusion data with ease, built for researchers and developers.

# Repository
repo_name: OSIPI/pypi
repo_url: https://github.com/OSIPI/pypi
copyright: Copyright © 2025 OSIPI Team  # Adjust year range as needed

# Configuration
theme:
  name: material
  logo: img/osipi.png  # Your logo
  favicon: img/favicon.ico  # Add a favicon if you have one
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book  # Adding a logo icon
  features:
    # Enhanced navigation and usability
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
  palette:
    # Multi-mode color scheme with toggle
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto  # Consistent typography
    code: Roboto Mono
  language: en

# Plugins
plugins:
  - search:  # Explicitly enable search with customization
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
  - gallery:
      examples_dirs: docs/examples
      gallery_dirs: docs/generated/gallery
  - minify:  # Optimize site load time
      minify_html: true

# Extra configuration
extra:
  social:  # Add social links
    - icon: fontawesome/brands/github
      link: https://github.com/OSIPI
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/OSIPI  # Replace with actual handle if applicable
  analytics:  # Optional: add analytics if desired
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY  # Set this in your environment

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: OSIPI
      repo: pypi
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Installation: user-guide/install.md
      - Simulating Data:
          - Overview: user-guide/simulate.md
          - Simulate AIF: user-guide/gen_aif.md
      - Fitting Data:
          - Overview: user-guide/fitting.md
          - Fit Tissue: user-guide/fit_tissue.md
  - Examples: generated/gallery
  - References:
      - Overview: references/index.md
      - Model Index: references/models/index.md
      - AIF Models:
          - Overview: references/models/aif_models/index.md
          - osipi.aif_parker: references/models/aif_models/aif_parker.md
          - osipi.aif_georgiou: references/models/aif_models/aif_georgiou.md
          - osipi.aif_weinmann: references/models/aif_models/aif_weinmann.md
      - Tissue Models:
          - Overview: references/models/tissue_models/index.md
          - osipi.tofts: references/models/tissue_models/tofts.md
          - osipi.extended_tofts: references/models/tissue_models/extended_tofts.md
  - Developer Guide: contribution/index.md
  - About: about/index.md